name: Build
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-2019
            dependencies: npm install
          - os: ubuntu-latest
            dependencies: apt-get install libusb-dev && apt-get install libudev-dev && npm install
          - os: macos-latest
            dependencies: brew install python-setuptools && npm install
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 90
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: ${{ matrix.config.dependencies }}
    - name: build
      run: npm run make      