name: Build
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]
        include:
          - os: windows-2019
            dependencies: npm install
          - os: ubuntu-latest
            # build-essential libudev-dev
            dependencies: sudo apt-get install libusb-dev && sudo apt-get install libudev-dev && npm install -g node-addon-api && npm install
          - os: macos-latest
            # dependencies: brew install python-setuptools && npm install -g node-addon-api && npm install
            dependencies: brew install python-setuptools && npm install
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    steps:
    - name: debug
      run: python3 -V && python -V
    - uses: actions/checkout@v3
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: ${{ matrix.dependencies }}
    - name: build
      run: npm run make      